services:
  - type: web
    name: campus-club-management
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_DRIVER
        value: org.postgresql.Driver
      - key: DDL_AUTO
        value: update
